"""Spatio-Temporal Event-Aware Waste Analytics - Sri Lanka

Production-ready, single-file Dash app that:
- Geocodes a curated set of Sri Lankan landmarks using Geopy/Nominatim (with 1s delay + caching)
- Pulls Sri Lanka holidays from Calendarific (with robust error handling + caching)
- Produces a research-focused, rule-based waste fill-level prediction
- Visualizes spatio-temporal waste hotspots on a Plotly Mapbox density map

Notes:
- Nominatim requires respectful usage: 1 request/second and a descriptive user_agent.
- Calendarific API key should be provided via environment variable CALENDARIFIC_API_KEY.

Author: (generated by GitHub Copilot)
"""

from __future__ import annotations

import json
import logging
import os
import random
import threading
import time
from dataclasses import dataclass
from datetime import date as Date, datetime, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import dash
from dash import Input, Output, dcc, html
import dash_bootstrap_components as dbc

import plotly.graph_objects as go

# Third-party HTTP + geocoding
import requests
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderServiceError, GeocoderTimedOut


# ------------------------------
# Configuration
# ------------------------------

APP_TITLE = "Spatio-Temporal Event-Aware Waste Analytics"
HEADER_TITLE = "Spatio-Temporal Event-Aware Waste Analytics - Sri Lanka"

# Curated landmarks as requested
LANDMARKS: List[str] = [
    "Ruwanwelisaya",
    "Temple of the Tooth (Kandy)",
    "Galle Face Green",
    "Fort Railway Station Colombo",
    "Kataragama Temple",
    "Nallathanniya (Sri Pada)",
]

# Some landmarks are better resolved by Nominatim using common/local names.
# We'll try these aliases in order until one resolves.
GEOCODE_ALIASES: Dict[str, List[str]] = {
    "Temple of the Tooth (Kandy)": [
        "Sri Dalada Maligawa, Kandy, Sri Lanka",
        "Temple of the Tooth, Kandy, Sri Lanka",
        "Dalada Maligawa, Kandy, Sri Lanka",
    ],
    "Kataragama Temple": [
        "Kataragama, Sri Lanka",
        "Kataragama Temple, Sri Lanka",
        "Kataragama Devalaya, Sri Lanka",
    ],
    "Fort Railway Station Colombo": [
        "Colombo Fort Railway Station, Sri Lanka",
        "Fort Railway Station, Colombo, Sri Lanka",
    ],
    "Ruwanwelisaya": [
        "Ruwanwelisaya, Anuradhapura, Sri Lanka",
        "Ruwanwelisaya, Sri Lanka",
    ],
    "Galle Face Green": [
        "Galle Face Green, Colombo, Sri Lanka",
        "Galle Face, Colombo, Sri Lanka",
    ],
    "Nallathanniya (Sri Pada)": [
        "Nallathanniya, Sri Lanka",
        "Sri Pada, Sri Lanka",
        "Adam's Peak, Sri Lanka",
    ],
}

# Landmark categories for the prediction rules
RELIGIOUS_SITES = {
    "Ruwanwelisaya",
    "Temple of the Tooth (Kandy)",
    "Kataragama Temple",
}
TRANSPORT_HUBS = {"Fort Railway Station Colombo"}
RECREATIONAL_PARKS = {"Galle Face Green"}
SEASONAL_PILGRIMAGE = {"Nallathanniya (Sri Pada)"}

# Caches stored alongside this file (still remains a single-file app; these are runtime artifacts)
APP_DIR = Path(__file__).resolve().parent
GEOCODE_CACHE_PATH = APP_DIR / "geocode_cache.json"
HOLIDAY_CACHE_PATH = APP_DIR / "holiday_cache.json"

# Calendarific
CALENDARIFIC_BASE_URL = "https://calendarific.com/api/v2/holidays"
CALENDARIFIC_COUNTRY = "LK"

# Requested years (we also support on-demand fetching for other years)
DEFAULT_HOLIDAY_YEARS = [2024, 2026]

# Map
SL_CENTER = (7.8731, 80.7718)

# Logging
logging.basicConfig(
    level=os.getenv("LOG_LEVEL", "INFO").upper(),
    format="%(asctime)s | %(levelname)s | %(message)s",
)
logger = logging.getLogger(__name__)

# Load environment variables from .env if python-dotenv is available.
# This keeps the app single-file while still allowing secrets to be stored outside code.
try:
    from dotenv import load_dotenv  # type: ignore

    load_dotenv(APP_DIR / ".env")
except Exception:
    # If python-dotenv isn't installed, we simply rely on OS environment variables.
    pass


# ------------------------------
# Data models
# ------------------------------

@dataclass(frozen=True)
class HolidayRecord:
    """Minimal holiday record we need for event detection."""

    name: str
    iso_date: str  # YYYY-MM-DD
    primary_type: str


@dataclass(frozen=True)
class EventFlags:
    """Flags describing how "eventful" a day is for waste generation."""

    is_public_holiday: bool
    is_poya: bool
    is_long_weekend: bool
    holiday_names: Tuple[str, ...]

    def summary_text(self) -> str:
        if not (self.is_public_holiday or self.is_poya or self.is_long_weekend):
            return "Normal day (no holiday detected)"

        labels: List[str] = []
        if self.is_poya:
            labels.append("Poya")
        if self.is_public_holiday:
            labels.append("Public Holiday")
        if self.is_long_weekend:
            labels.append("Long Weekend")

        names = ", ".join(self.holiday_names) if self.holiday_names else "—"
        return f"{' / '.join(labels)} | {names}"


# ------------------------------
# Geocoding (Geopy + Nominatim)
# ------------------------------

def _load_json(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as ex:  # noqa: BLE001
        logger.warning("Failed to read JSON cache %s: %s", path, ex)
        return {}


def _save_json(path: Path, payload: Dict[str, Any]) -> None:
    try:
        path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    except Exception as ex:  # noqa: BLE001
        logger.warning("Failed to write JSON cache %s: %s", path, ex)


def geocode_landmarks(landmarks: List[str]) -> Dict[str, Tuple[float, float]]:
    """Geocode landmarks via Nominatim with 1-second delay and caching.

    Returns a dict mapping location_name -> (lat, lon) for successfully geocoded locations.

    Implementation details:
    - Uses time.sleep(1) between API calls (Nominatim rate limiting)
    - Uses in-memory dict cache, with optional persistence to JSON for faster restarts
    - Robust error handling: failures are logged and skipped
    """

    # Load persisted cache first (dictionary cache requirement is still met; this is just persistence)
    persisted_cache = _load_json(GEOCODE_CACHE_PATH)

    # In-memory cache (requested)
    coords_cache: Dict[str, Tuple[float, float]] = {}

    # Hydrate from disk
    for k, v in persisted_cache.items():
        try:
            coords_cache[k] = (float(v[0]), float(v[1]))
        except Exception:  # noqa: BLE001
            continue

    # Create a descriptive user_agent as recommended by Nominatim
    geolocator = Nominatim(user_agent="spatio_temporal_waste_analytics_dashboard")

    updated = False
    for name in landmarks:
        if name in coords_cache:
            continue

        # Try aliases first (more reliable), then fallback query.
        queries = GEOCODE_ALIASES.get(name, []) + [f"{name}, Sri Lanka"]
        try:
            # Respect Nominatim usage policy and prevent concurrent requests.

            location = None
            for query in queries:
                with _GEOCODE_REQUEST_LOCK:
                    time.sleep(1)
                    location = geolocator.geocode(query, timeout=15)

                if location is not None:
                    break

            if location is None:
                logger.warning("Geocoding returned no result for: %s", queries[0])
                continue

            coords_cache[name] = (float(location.latitude), float(location.longitude))
            updated = True
            logger.info("Geocoded %s -> (%.6f, %.6f)", name, location.latitude, location.longitude)

        except (GeocoderTimedOut, GeocoderServiceError) as ex:
            logger.warning("Geocoding error for %s: %s", query, ex)
        except Exception as ex:  # noqa: BLE001
            logger.exception("Unexpected geocoding failure for %s: %s", query, ex)

    if updated:
        _save_json(GEOCODE_CACHE_PATH, {k: list(v) for k, v in coords_cache.items()})

    return coords_cache


def load_geocode_cache() -> Dict[str, Tuple[float, float]]:
    """Load geocode cache from disk without making network calls."""

    persisted_cache = _load_json(GEOCODE_CACHE_PATH)
    coords_cache: Dict[str, Tuple[float, float]] = {}
    for k, v in persisted_cache.items():
        try:
            coords_cache[k] = (float(v[0]), float(v[1]))
        except Exception:  # noqa: BLE001
            continue
    return coords_cache


# ------------------------------
# Calendarific integration
# ------------------------------

def _calendarific_api_key() -> Optional[str]:
    """Get Calendarific API key from env.

    For security, do not hardcode secrets in production.
    """

    key = os.getenv("CALENDARIFIC_API_KEY", "").strip()
    return key or None


def _parse_calendarific_holidays(payload: Dict[str, Any]) -> List[HolidayRecord]:
    """Parse Calendarific response into HolidayRecord list."""

    holidays: List[HolidayRecord] = []
    response = payload.get("response", {})
    for h in response.get("holidays", []) or []:
        try:
            name = str(h.get("name", "")).strip()
            iso_date = str(((h.get("date") or {}).get("iso", ""))).strip()
            types = h.get("type") or []
            primary_type = str(types[0]) if types else "Unknown"

            if name and iso_date:
                holidays.append(HolidayRecord(name=name, iso_date=iso_date, primary_type=primary_type))
        except Exception:  # noqa: BLE001
            continue

    return holidays


def fetch_sri_lanka_holidays(years: List[int]) -> Dict[int, List[HolidayRecord]]:
    """Fetch Sri Lanka holidays for the specified years from Calendarific.

    Requirements implemented:
    - Robust error handling for API requests
    - Uses cache to avoid repeated API calls
    """

    # Load cache
    cached = _load_json(HOLIDAY_CACHE_PATH)
    holiday_by_year: Dict[int, List[HolidayRecord]] = {}

    # Hydrate from cache
    for year_str, records in (cached or {}).items():
        try:
            y = int(year_str)
            holiday_by_year[y] = [HolidayRecord(**r) for r in (records or [])]
        except Exception:  # noqa: BLE001
            continue

    api_key = _calendarific_api_key()
    if not api_key:
        logger.warning(
            "Calendarific API key not found. Set CALENDARIFIC_API_KEY to enable holiday detection."
        )
        return holiday_by_year

    updated = False

    for year in years:
        if year in holiday_by_year and holiday_by_year[year]:
            continue

        try:
            with _HOLIDAY_FETCH_LOCK:
                resp = requests.get(
                    CALENDARIFIC_BASE_URL,
                    params={
                        "api_key": api_key,
                        "country": CALENDARIFIC_COUNTRY,
                        "year": year,
                    },
                    timeout=20,
                )
            if resp.status_code != 200:
                logger.warning("Calendarific returned %s: %s", resp.status_code, resp.text[:300])
                continue

            payload = resp.json()
            records = _parse_calendarific_holidays(payload)
            holiday_by_year[year] = records
            updated = True
            logger.info("Fetched %d holidays for Sri Lanka (%d)", len(records), year)

        except requests.RequestException as ex:
            logger.warning("Calendarific request error for year %d: %s", year, ex)
        except Exception as ex:  # noqa: BLE001
            logger.exception("Unexpected Calendarific failure for year %d: %s", year, ex)

    if updated:
        # Save to disk in serializable form
        serializable = {
            str(y): [r.__dict__ for r in rs]
            for y, rs in holiday_by_year.items()
            if rs
        }
        _save_json(HOLIDAY_CACHE_PATH, serializable)

    return holiday_by_year


def load_holiday_cache() -> Dict[int, List[HolidayRecord]]:
    """Load holiday cache from disk without making network calls."""

    cached = _load_json(HOLIDAY_CACHE_PATH)
    holiday_by_year: Dict[int, List[HolidayRecord]] = {}
    for year_str, records in (cached or {}).items():
        try:
            y = int(year_str)
            holiday_by_year[y] = [HolidayRecord(**r) for r in (records or [])]
        except Exception:  # noqa: BLE001
            continue
    return holiday_by_year


def _holiday_records_for_date(holiday_by_year: Dict[int, List[HolidayRecord]], d: Date) -> List[HolidayRecord]:
    """Return holiday records that match this date."""

    records = holiday_by_year.get(d.year, [])
    iso = d.isoformat()
    return [r for r in records if r.iso_date == iso]


def _is_poya_holiday_name(name: str) -> bool:
    return "poya" in name.lower()


def _is_festival_holiday_name(name: str) -> bool:
    # Heuristic: many holidays include 'Festival', 'Eid', 'Christmas', etc.
    lowered = name.lower()
    return any(
        kw in lowered
        for kw in [
            "festival",
            "vesak",
            "poson",
            "esala",
            "deepavali",
            "diwali",
            "thai pongal",
            "eid",
            "christmas",
            "new year",
        ]
    )


def is_event_day(holiday_by_year: Dict[int, List[HolidayRecord]], target_date: Date) -> EventFlags:
    """Determine whether the date is a Poya day, a public holiday, or part of a long weekend.

    Long-weekend rule (requested example):
    - If Friday is a holiday, treat Fri/Sat/Sun as high-impact.
    - If Monday is a holiday, treat Sat/Sun/Mon as high-impact.
    """

    todays = _holiday_records_for_date(holiday_by_year, target_date)
    holiday_names = tuple(sorted({r.name for r in todays}))

    is_poya = any(_is_poya_holiday_name(r.name) for r in todays)

    # Treat anything returned by Calendarific as a public holiday for this research-oriented dashboard.
    # We also mark days as public-holiday-like if they look like festivals.
    is_public_holiday = bool(todays) or any(_is_festival_holiday_name(n) for n in holiday_names)

    # Long weekend detection (requested example logic)
    # - If Friday is a holiday => Fri/Sat/Sun become high-impact
    # - If Monday is a holiday => Sat/Sun/Mon become high-impact
    is_long_weekend = False

    weekday = target_date.weekday()  # Mon=0 ... Sun=6

    def has_holiday(d: Date) -> bool:
        return bool(_holiday_records_for_date(holiday_by_year, d))

    # Friday-anchored long weekend
    if weekday in (4, 5, 6):
        friday = target_date - timedelta(days=(weekday - 4))
        if has_holiday(friday):
            is_long_weekend = True

    # Monday-anchored long weekend
    if weekday in (5, 6, 0):
        if weekday == 0:
            monday = target_date
        elif weekday == 5:  # Saturday
            monday = target_date + timedelta(days=2)
        else:  # Sunday
            monday = target_date + timedelta(days=1)

        if has_holiday(monday):
            is_long_weekend = True

    return EventFlags(
        is_public_holiday=is_public_holiday,
        is_poya=is_poya,
        is_long_weekend=is_long_weekend,
        holiday_names=holiday_names,
    )


# ------------------------------
# Prediction engine (rule-based)
# ------------------------------

def _stable_rng(location_name: str, d: Date) -> random.Random:
    """Stable RNG so the same date/location yields the same output (reproducibility)."""

    seed = f"{location_name}|{d.isoformat()}"
    return random.Random(seed)


def _rand_int(rng: random.Random, lo: int, hi: int) -> int:
    return int(rng.randint(lo, hi))


def calculate_waste_impact(
    location_name: str,
    d: Date,
    flags: EventFlags,
) -> int:
    """Calculate predicted waste fill level (0-100) for a location and date.

    Rules implemented from prompt:
    - Religious Sites: If Poya or Festival -> 90-100%
    - Transport Hubs: If Sunday or Public Holiday -> 85-95%
    - Recreational Parks: If Weekend -> 80-90%
    - Seasonal (Sri Pada/Nallathanniya): Dec-May baseline 80%, spike to 100% on Poya
    - Default baseline: 30-50%

    We also treat "long weekend" as holiday-like, increasing impact.
    """

    rng = _stable_rng(location_name, d)
    weekday = d.weekday()  # Mon=0 ... Sun=6
    is_weekend = weekday in (5, 6)
    is_sunday = weekday == 6

    # Treat long weekend as high-impact holiday context
    holiday_like = flags.is_public_holiday or flags.is_long_weekend
    festival_like = flags.is_poya or flags.is_public_holiday

    # Seasonal pilgrimage logic has priority for Sri Pada
    if location_name in SEASONAL_PILGRIMAGE:
        in_season = d.month in (12, 1, 2, 3, 4, 5)
        if in_season:
            if flags.is_poya:
                return 100
            # Baseline 80% (slight variability for realism)
            return _rand_int(rng, 78, 85)

        # Off-season: calmer baseline
        return _rand_int(rng, 35, 55)

    # Religious sites
    if location_name in RELIGIOUS_SITES:
        if flags.is_poya or festival_like:
            return _rand_int(rng, 90, 100)
        return _rand_int(rng, 35, 55)

    # Transport hubs
    if location_name in TRANSPORT_HUBS:
        if is_sunday or holiday_like:
            return _rand_int(rng, 85, 95)
        return _rand_int(rng, 40, 60)

    # Recreational parks
    if location_name in RECREATIONAL_PARKS:
        if is_weekend:
            return _rand_int(rng, 80, 90)
        return _rand_int(rng, 35, 55)

    # Default
    return _rand_int(rng, 30, 50)


# ------------------------------
# Visualization helpers
# ------------------------------

def build_map_figure(rows: List[Dict[str, Any]]) -> go.Figure:
    """Create a density_mapbox + scatter overlay for interpretability."""

    lats = [r["lat"] for r in rows]
    lons = [r["lon"] for r in rows]
    z = [r["fill_level"] for r in rows]
    labels = [r["location"] for r in rows]

    fig = go.Figure()

    # Density layer (heatmap)
    fig.add_trace(
        go.Densitymapbox(
            lat=lats,
            lon=lons,
            z=z,
            radius=35,
            colorscale="YlOrRd",
            zmin=0,
            zmax=100,
            hoverinfo="skip",
            name="Fill Density",
            showscale=True,
            colorbar=dict(title="Fill %"),
        )
    )

    # Scatter overlay (exact points + hover text)
    fig.add_trace(
        go.Scattermapbox(
            lat=lats,
            lon=lons,
            mode="markers+text",
            text=[f"{lvl}%" for lvl in z],
            textposition="top center",
            marker=dict(size=14, color=z, colorscale="YlOrRd", cmin=0, cmax=100, opacity=0.9),
            hovertemplate="<b>%{customdata}</b><br>Fill: %{marker.color}%<extra></extra>",
            customdata=labels,
            name="Locations",
        )
    )

    fig.update_layout(
        margin=dict(l=0, r=0, t=0, b=0),
        mapbox=dict(
            style="open-street-map",
            center=dict(lat=SL_CENTER[0], lon=SL_CENTER[1]),
            zoom=6.2,
        ),
        legend=dict(orientation="h", yanchor="bottom", y=0.01, xanchor="left", x=0.01),
    )

    return fig


def build_actionable_insights(rows: List[Dict[str, Any]]) -> List[html.Li]:
    """Generate actionable insights for the sidebar."""

    items: List[html.Li] = []

    # Sort descending by fill level
    sorted_rows = sorted(rows, key=lambda r: r["fill_level"], reverse=True)

    for r in sorted_rows:
        loc = r["location"]
        lvl = int(r["fill_level"])

        if lvl >= 90:
            bins = 5
            items.append(
                html.Li(
                    [
                        "⚠️ ",
                        html.B(f"ALERT: {loc}"),
                        f" exceeding 90% threshold ({lvl}%). ",
                        html.I(f"Recommended: Deploy {bins} temporary bins."),
                    ]
                )
            )
        elif lvl >= 80:
            bins = 3
            items.append(
                html.Li(
                    [
                        "⚠️ ",
                        html.B(f"WATCH: {loc}"),
                        f" high utilization ({lvl}%). ",
                        html.I(f"Recommended: Add {bins} extra bins and increase collection frequency."),
                    ]
                )
            )

    if not items:
        items.append(html.Li("No critical alerts for the selected date. Maintain standard operations."))

    return items


# ------------------------------
# App initialization
# ------------------------------

# Load caches quickly on startup; do not block the UI with network calls.
# Missing values will be fetched/geocoded on-demand (and optionally in background).
COORDS: Dict[str, Tuple[float, float]] = load_geocode_cache()
HOLIDAYS_BY_YEAR: Dict[int, List[HolidayRecord]] = load_holiday_cache()

# Simple locks for thread-safe cache updates
_COORDS_LOCK = threading.Lock()
_HOLIDAYS_LOCK = threading.Lock()

# Serialize outbound requests across threads
_GEOCODE_REQUEST_LOCK = threading.Lock()
_HOLIDAY_FETCH_LOCK = threading.Lock()

# Track in-flight work to prevent duplicate background tasks
_PENDING_GEOCODES: set[str] = set()
_PENDING_HOLIDAY_YEARS: set[int] = set()


def _request_geocoding(names: List[str]) -> None:
    """Kick off best-effort geocoding for any missing landmarks (deduplicated)."""

    to_fetch: List[str] = []
    with _COORDS_LOCK:
        for n in names:
            if n in COORDS or n in _PENDING_GEOCODES:
                continue
            _PENDING_GEOCODES.add(n)
            to_fetch.append(n)

    if not to_fetch:
        return

    def worker(batch: List[str]) -> None:
        try:
            new_coords = geocode_landmarks(batch)
            with _COORDS_LOCK:
                COORDS.update(new_coords)
        finally:
            with _COORDS_LOCK:
                for n in batch:
                    _PENDING_GEOCODES.discard(n)

    threading.Thread(target=worker, args=(to_fetch,), daemon=True).start()


def _request_holidays(years: List[int]) -> None:
    """Kick off best-effort holiday fetching for missing years (deduplicated)."""

    to_fetch: List[int] = []
    with _HOLIDAYS_LOCK:
        for y in years:
            if y in HOLIDAYS_BY_YEAR or y in _PENDING_HOLIDAY_YEARS:
                continue
            _PENDING_HOLIDAY_YEARS.add(y)
            to_fetch.append(y)

    if not to_fetch:
        return

    def worker(batch: List[int]) -> None:
        try:
            new_holidays = fetch_sri_lanka_holidays(batch)
            if new_holidays:
                with _HOLIDAYS_LOCK:
                    HOLIDAYS_BY_YEAR.update(new_holidays)
        finally:
            with _HOLIDAYS_LOCK:
                for y in batch:
                    _PENDING_HOLIDAY_YEARS.discard(y)

    threading.Thread(target=worker, args=(to_fetch,), daemon=True).start()


def _background_prefetch() -> None:
    """Best-effort prefetch of missing geocodes + holidays in a background thread."""

    try:
        _request_geocoding(LANDMARKS)
        _request_holidays(DEFAULT_HOLIDAY_YEARS)

    except Exception as ex:  # noqa: BLE001
        logger.warning("Background prefetch failed: %s", ex)


# Start background prefetch (daemon thread so it won't block shutdown)
threading.Thread(target=_background_prefetch, daemon=True).start()


def _compute_rows_for_date(selected: Date) -> Tuple[List[Dict[str, Any]], EventFlags]:
    """Compute the rows needed by the map and insights for a given date."""

    # Ensure we have holidays for the year (on-demand, non-blocking)
    with _HOLIDAYS_LOCK:
        has_year = selected.year in HOLIDAYS_BY_YEAR
    if not has_year:
        _request_holidays([selected.year])

    with _HOLIDAYS_LOCK:
        flags = is_event_day(HOLIDAYS_BY_YEAR, selected)

    rows: List[Dict[str, Any]] = []
    missing_coords: List[str] = []
    for loc in LANDMARKS:
        with _COORDS_LOCK:
            coord = COORDS.get(loc)
        if not coord:
            missing_coords.append(loc)
            continue

        fill = calculate_waste_impact(loc, selected, flags)
        rows.append(
            {
                "location": loc,
                "lat": coord[0],
                "lon": coord[1],
                "fill_level": fill,
            }
        )

    # Trigger background geocoding for missing landmarks (non-blocking)
    if missing_coords:
        _request_geocoding(missing_coords)

    return rows, flags


def _fmt_date(d: Optional[str]) -> str:
    if not d:
        return "—"
    try:
        parsed = datetime.fromisoformat(d).date()
        return parsed.strftime("%Y-%m-%d")
    except Exception:  # noqa: BLE001
        return str(d)


# ------------------------------
# Dash UI
# ------------------------------

app = dash.Dash(
    __name__,
    external_stylesheets=[dbc.themes.FLATLY],
    title=APP_TITLE,
    suppress_callback_exceptions=True,
)


def make_card(title: str, body_id: str) -> dbc.Card:
    return dbc.Card(
        [
            dbc.CardHeader(html.Div(title, className="fw-semibold")),
            dbc.CardBody(html.Div(id=body_id, className="fs-5")),
        ],
        className="shadow-sm",
    )


app.layout = dbc.Container(
    fluid=True,
    children=[
        dbc.Row(
            [
                dbc.Col(
                    [
                        html.H2(HEADER_TITLE, className="mt-3 mb-2"),
                        html.Div(
                            "Research-focused dashboard combining events, holidays, and spatial context.",
                            className="text-muted mb-3",
                        ),
                    ]
                )
            ]
        ),
        dbc.Row(
            [
                dbc.Col(make_card("Selected Date", "card-selected-date"), md=4),
                dbc.Col(make_card("Holiday / Event Status", "card-holiday-status"), md=4),
                dbc.Col(make_card("Global Average Fill Level", "card-global-average"), md=4),
            ],
            className="g-3",
        ),
        dbc.Row(
            [
                dbc.Col(
                    [
                        dbc.Card(
                            [
                                dbc.CardHeader(
                                    dbc.Row(
                                        [
                                            dbc.Col(html.Div("Waste Hotspot Heatmap", className="fw-semibold")),
                                            dbc.Col(
                                                dcc.DatePickerSingle(
                                                    id="date-picker",
                                                    date=Date.today().isoformat(),
                                                    display_format="YYYY-MM-DD",
                                                    className="float-end",
                                                ),
                                                width="auto",
                                            ),
                                        ],
                                        align="center",
                                    )
                                ),
                                dbc.CardBody(
                                    dcc.Graph(
                                        id="heatmap",
                                        style={"height": "70vh"},
                                        config={"displayModeBar": True},
                                    )
                                ),
                            ],
                            className="shadow-sm",
                        )
                    ],
                    md=8,
                ),
                dbc.Col(
                    [
                        dbc.Card(
                            [
                                dbc.CardHeader(html.Div("Actionable Insights", className="fw-semibold")),
                                dbc.CardBody(
                                    [
                                        html.Ul(id="insights-list", className="mb-0"),
                                        html.Hr(),
                                        dbc.Alert(
                                            [
                                                html.B("Note:"),
                                                " Predictions are rule-based and intended for research exploration. ",
                                                "Connect real IoT bin sensors to operationalize.",
                                            ],
                                            color="info",
                                            className="mb-0",
                                        ),
                                    ]
                                ),
                            ],
                            className="shadow-sm",
                        ),
                    ],
                    md=4,
                ),
            ],
            className="g-3 mt-1",
        ),
        dbc.Row(
            [
                dbc.Col(
                    html.Div(
                        [
                            html.Small(
                                [
                                    "Aligned with ",
                                    html.B("SDG 11"),
                                    ": Sustainable Cities and Communities.",
                                ],
                                className="text-muted",
                            )
                        ],
                        className="text-center my-3",
                    )
                )
            ]
        ),
    ],
)


# ------------------------------
# Callbacks
# ------------------------------

@app.callback(
    Output("card-selected-date", "children"),
    Output("card-holiday-status", "children"),
    Output("card-global-average", "children"),
    Output("heatmap", "figure"),
    Output("insights-list", "children"),
    Input("date-picker", "date"),
)
def update_dashboard(date_str: Optional[str]):
    """Update the dashboard when the date changes."""

    if not date_str:
        selected = Date.today()
    else:
        try:
            selected = datetime.fromisoformat(date_str).date()
        except Exception:
            selected = Date.today()

    rows, flags = _compute_rows_for_date(selected)

    # If holiday data for this year isn't loaded yet, present a "loading" hint.
    with _HOLIDAYS_LOCK:
        holiday_year_ready = selected.year in HOLIDAYS_BY_YEAR and bool(HOLIDAYS_BY_YEAR.get(selected.year))

    holiday_text = flags.summary_text() if holiday_year_ready else "Loading holiday data…"

    # If any landmarks are missing coordinates, geocoding might still be in progress.
    with _COORDS_LOCK:
        missing_count = sum(1 for l in LANDMARKS if l not in COORDS)

    if rows:
        avg = sum(r["fill_level"] for r in rows) / len(rows)
        avg_text = f"{avg:.1f}%"
    else:
        avg_text = "—"

    fig = build_map_figure(rows) if rows else go.Figure()
    if not rows:
        fig.update_layout(
            annotations=[
                dict(
                    text="No geocoded points available (check geocoding + internet access).",
                    x=0.5,
                    y=0.5,
                    showarrow=False,
                    xref="paper",
                    yref="paper",
                )
            ]
        )
    elif missing_count:
        fig.update_layout(
            annotations=[
                dict(
                    text=f"Geocoding in progress for {missing_count} location(s)…",
                    x=0.5,
                    y=0.02,
                    showarrow=False,
                    xref="paper",
                    yref="paper",
                    font=dict(size=12, color="#555"),
                )
            ]
        )

    insights = build_actionable_insights(rows)

    return (
        _fmt_date(date_str),
        holiday_text,
        avg_text,
        fig,
        insights,
    )


# ------------------------------
# Entrypoint
# ------------------------------

if __name__ == "__main__":
    # Dash recommends using debug=False for production.
    # You can set DASH_DEBUG=1 for local development.
    debug = os.getenv("DASH_DEBUG", "0").strip() == "1"
    host = os.getenv("HOST", "0.0.0.0")
    port = int(os.getenv("PORT", "8050"))

    # Dash 4+ uses app.run(); older Dash uses app.run_server().
    run_fn = getattr(app, "run", None) or getattr(app, "run_server", None)
    if run_fn is None:
        raise RuntimeError("Unable to start Dash server: no run method found on Dash app")

    run_fn(host=host, port=port, debug=debug)
